### ISSUE TITLE
MixinBooter 11.x crashes dedicated server with NoClassDefFoundError: EntityPlayerSP (10.7 silently fails to apply mixins)

### ISSUE THREAD

**Issue by zxy-pixel** [CleanroomMC/MixinBooter#144]
### Version

11.15

### Platform

Windows x64

### Java Version

8

### Description

Environment

Minecraft: 1.12.2

Forge: 14.23.5.2864

MixinBooter versions tested: 10.7, 11.0, 11.12, 11.15

Problem description

On a dedicated server, MixinBooter exhibits two different failure modes depending on the version:

With MixinBooter 10.7: The server starts without crashing, but mixins are not applied – no transformation takes effect. No error is logged, but the expected behavior is missing.

With MixinBooter 11.x (including 11.0, 11.12, and 11.15): The server crashes during mod construction with a NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP. The stack trace indicates that Forge's SideTransformer is attempting to load a client‑only class on the server side.

Full crash log snippet

text
java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
...
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
Caused by: java.lang.RuntimeException: Attempted to load class bud for invalid side SERVER
What I've already tried

Tested with a minimal test mod containing only one simple Mixin – same result.

Clean builds with gradlew clean build to ensure no corrupted jars.

Verified that the same setup works correctly in a single‑player (integrated server) environment with MixinBooter 11.x.

Expected behavior

MixinBooter 11.x should function on a dedicated server without crashing, similarly to how it works on the client.

MixinBooter 10.7 should apply mixins correctly, not silently ignore them.

Additional notes
The crash does not occur when MixinBooter 11.x is used in an integrated server (single‑player), which suggests the issue is specific to the dedicated server environment. It appears that MixinBooter 11.x changed the way it handles side‑only class filtering or Mixin scanning, causing it to inadvertently attempt to load client classes on the server side.

I have not been able to find any intermediate version between 10.7 and 11.0 that works correctly on a dedicated server – 11.0 itself already crashes with the same error.

Please let me know if you need any additional logs or test builds to reproduce the issue.

Thank you for maintaining MixinBooter!

### Crash Reports or Log Files

[crash-2026-08-22_22.41.34-server.txt](https://github.com/user-attachments/files/31335439/crash-2026-08-22_22.41.34-server.txt)

**Comment by Rongmario** [comment]
What is your "minimal test mod containing only one simple Mixin", the crash report won't help with anything.

**Comment by zxy-pixel** [comment]
That's because the translation tool sneaked in extra stuff on its own. Let me put it this way. This time I will provide an environment that is easy to test and reproduce: using the RLCraft 2.9.3 modpack. With almost no other changes, under the original mod settings from the original author, simply adding your mixinbooter 11.15 and Phosphor Crash Fix mod to the mods folder will definitely cause the Forge server to crash.

The reason for adding Phosphor Crash Fix is that the original modpack uses Phosphor, the lighting optimization mod, and it is not very compatible with mixinbooter. Even with mixinbooter 10.7, without adding Phosphor Crash Fix, it will definitely crash as well. Phosphor Crash Fix can be downloaded directly from CurseForge. Its purpose is: "A simple coremod that fixes the crashes caused by Phosphor's outdated injection annotations when using versions of mixin newer than 0.7.x."

I am providing a new crash log this time. Please check it.

[crash-2026-08-23_11.46.49-server.txt](https://github.com/user-attachments/files/31343036/crash-2026-08-23_11.46.49-server.txt)

**Comment by zxy-pixel** [comment]
I also discovered that even without adding Phosphor Crash Fix, simply removing the Phosphor lighting optimization mod from the original RLCraft modpack and then adding only mixinbooter 11.x will still cause the Forge server to crash every time. Phosphor is not a core mod in the RLCraft modpack – removing it under the original pack's configuration still allows the server to start normally without any other mods added. Additionally, the RLCraft Dregora branch modpack also includes Phosphor Crash Fix, and with only mixinbooter 11.x added, the same server crashes without fail. The carsh log has exactly the same reason

**Comment by zxy-pixel** [comment]
After a few more hours of troubleshooting, I found the root cause. Turns out it's not entirely your issue – it's the common author of the RLCraft and RLCraft Dregora modpacks who mistakenly included three client‑only mods (BlockOverlayFix, RenderLib, Entity Culling) in the server package, and MixinBooter 11+ caught them, causing consistent crashes.

Among them, BlockOverlayFix was the main culprit – it kept crashing the server due to the EntityPlayerSP class. After removing it, the following error popped up:
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RenderLib (renderlib)
Caused by: java.lang.NoClassDefFoundError: org/lwjgl/opengl/GLContext
at meldexun.renderlib.util.GLUtil.init(GLUtil.java:30)
at meldexun.renderlib.RenderLib.onFMLConstructionEvent(RenderLib.java:34)
Another client‑only mod, Entity Culling, depends on RenderLib. After removing both, the Forge server starts normally.

Sorry for bothering you.
